config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/',include('pybo.urls')),
]

pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
    path('',views.index,name='index'),
    path('<int:question_id>/',views.detail,name='detail'),    
]

pybo/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

pybo/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Question
# Create your views here.

from django.shortcuts import render


def index(request):
    
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list':question_list}   
    return render(request,'pybo/question_list.html',context)
    # return render(request,'pybo/base.html',context)

def detail(request,question_id):

    qes = Question.objects.get(id=question_id)
    context = {'question':qes}
    return render(request,'pybo/question_detail.html',context)

templates/pybo/base.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <title>hello!</title>
  </head>
  <header class="page-header">
    <div class="container">
      <h1><a href="/">Django Girls Blog</a></h1>
    </div>
  </header>
  <body>
    {% block content %} 이상해 {% endblock %}
  </body>
</html>

templates/pybo/question_detail.html
<h1>{{question.subject}}</h1>

<p>{{question.content}}</p>

templates/pybo/question_list.html
{% extends "pybo/base.html" %} {% block content %} {% if question_list %}
<ul>
  {% for question in question_list %}
  <li>
    <a href="{% url 'pybo:detail' question.id %}">{{question.subject}}</a>
  </li>
  {% endfor %}
</ul>
{% else %}
<p>질문이 없습니다</p>
{% endif %} {% endblock %}

templates/pybo/register.html
{% extedns "base.html" %} {% block contents %}

<h1>회원가입</h1>
<div class="col-12">
  <form method="POST">
    <label for="username">사용자 이름 입력</label>
    <input type="text" id="username" placeholder="사용자 입력" />
    <label for="password">비밀번호 입력</label>
    <input type="password" id="password" />
  </form>
</div>

{% endlock %}